// Code generated by protoc-gen-go.
// source: easel_service.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	easel_service.proto

It has these top-level messages:
	NewEaselRequest
	NewEaselResponse
	DeleteEaselRequest
	DeleteEaselResponse
	NewPaletteRequest
	NewPaletteResponse
	DeletePaletteRequest
	DeletePaletteResponse
	VertexAttribute
	UniformFloatValue
	UniformIntValue
	UniformTexture
	UniformVariable
	ArrayBuffer
	PaletteStates
	UpdatePaletteRequest
	UpdatePaletteResponse
	RenderRequest
	RenderResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NewEaselRequest struct {
	EaselId string `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
}

func (m *NewEaselRequest) Reset()                    { *m = NewEaselRequest{} }
func (m *NewEaselRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewEaselRequest) ProtoMessage()               {}
func (*NewEaselRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewEaselRequest) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

type NewEaselResponse struct {
	EaselId string `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
}

func (m *NewEaselResponse) Reset()                    { *m = NewEaselResponse{} }
func (m *NewEaselResponse) String() string            { return proto1.CompactTextString(m) }
func (*NewEaselResponse) ProtoMessage()               {}
func (*NewEaselResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewEaselResponse) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

type DeleteEaselRequest struct {
	EaselId string `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
}

func (m *DeleteEaselRequest) Reset()                    { *m = DeleteEaselRequest{} }
func (m *DeleteEaselRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteEaselRequest) ProtoMessage()               {}
func (*DeleteEaselRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteEaselRequest) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

type DeleteEaselResponse struct {
}

func (m *DeleteEaselResponse) Reset()                    { *m = DeleteEaselResponse{} }
func (m *DeleteEaselResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteEaselResponse) ProtoMessage()               {}
func (*DeleteEaselResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type NewPaletteRequest struct {
	EaselId string `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
}

func (m *NewPaletteRequest) Reset()                    { *m = NewPaletteRequest{} }
func (m *NewPaletteRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewPaletteRequest) ProtoMessage()               {}
func (*NewPaletteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NewPaletteRequest) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

type NewPaletteResponse struct {
	EaselId   string `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
	PaletteId string `protobuf:"bytes,2,opt,name=palette_id,json=paletteId" json:"palette_id,omitempty"`
}

func (m *NewPaletteResponse) Reset()                    { *m = NewPaletteResponse{} }
func (m *NewPaletteResponse) String() string            { return proto1.CompactTextString(m) }
func (*NewPaletteResponse) ProtoMessage()               {}
func (*NewPaletteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NewPaletteResponse) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

func (m *NewPaletteResponse) GetPaletteId() string {
	if m != nil {
		return m.PaletteId
	}
	return ""
}

type DeletePaletteRequest struct {
	EaselId   string `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
	PaletteId string `protobuf:"bytes,2,opt,name=palette_id,json=paletteId" json:"palette_id,omitempty"`
}

func (m *DeletePaletteRequest) Reset()                    { *m = DeletePaletteRequest{} }
func (m *DeletePaletteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeletePaletteRequest) ProtoMessage()               {}
func (*DeletePaletteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeletePaletteRequest) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

func (m *DeletePaletteRequest) GetPaletteId() string {
	if m != nil {
		return m.PaletteId
	}
	return ""
}

type DeletePaletteResponse struct {
}

func (m *DeletePaletteResponse) Reset()                    { *m = DeletePaletteResponse{} }
func (m *DeletePaletteResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeletePaletteResponse) ProtoMessage()               {}
func (*DeletePaletteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type VertexAttribute struct {
	ArgumentName string `protobuf:"bytes,1,opt,name=argument_name,json=argumentName" json:"argument_name,omitempty"`
	BufferName   string `protobuf:"bytes,2,opt,name=buffer_name,json=bufferName" json:"buffer_name,omitempty"`
	ElementSize  int32  `protobuf:"varint,3,opt,name=element_size,json=elementSize" json:"element_size,omitempty"`
	Offset       int32  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	Stride       int32  `protobuf:"varint,5,opt,name=stride" json:"stride,omitempty"`
}

func (m *VertexAttribute) Reset()                    { *m = VertexAttribute{} }
func (m *VertexAttribute) String() string            { return proto1.CompactTextString(m) }
func (*VertexAttribute) ProtoMessage()               {}
func (*VertexAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *VertexAttribute) GetArgumentName() string {
	if m != nil {
		return m.ArgumentName
	}
	return ""
}

func (m *VertexAttribute) GetBufferName() string {
	if m != nil {
		return m.BufferName
	}
	return ""
}

func (m *VertexAttribute) GetElementSize() int32 {
	if m != nil {
		return m.ElementSize
	}
	return 0
}

func (m *VertexAttribute) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *VertexAttribute) GetStride() int32 {
	if m != nil {
		return m.Stride
	}
	return 0
}

type UniformFloatValue struct {
	ElementSize int32     `protobuf:"varint,1,opt,name=element_size,json=elementSize" json:"element_size,omitempty"`
	Data        []float32 `protobuf:"fixed32,2,rep,packed,name=data" json:"data,omitempty"`
}

func (m *UniformFloatValue) Reset()                    { *m = UniformFloatValue{} }
func (m *UniformFloatValue) String() string            { return proto1.CompactTextString(m) }
func (*UniformFloatValue) ProtoMessage()               {}
func (*UniformFloatValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UniformFloatValue) GetElementSize() int32 {
	if m != nil {
		return m.ElementSize
	}
	return 0
}

func (m *UniformFloatValue) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type UniformIntValue struct {
	ElementSize int32   `protobuf:"varint,1,opt,name=element_size,json=elementSize" json:"element_size,omitempty"`
	Data        []int32 `protobuf:"varint,2,rep,packed,name=data" json:"data,omitempty"`
}

func (m *UniformIntValue) Reset()                    { *m = UniformIntValue{} }
func (m *UniformIntValue) String() string            { return proto1.CompactTextString(m) }
func (*UniformIntValue) ProtoMessage()               {}
func (*UniformIntValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UniformIntValue) GetElementSize() int32 {
	if m != nil {
		return m.ElementSize
	}
	return 0
}

func (m *UniformIntValue) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type UniformTexture struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *UniformTexture) Reset()                    { *m = UniformTexture{} }
func (m *UniformTexture) String() string            { return proto1.CompactTextString(m) }
func (*UniformTexture) ProtoMessage()               {}
func (*UniformTexture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UniformTexture) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UniformVariable struct {
	Name       string             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FloatValue *UniformFloatValue `protobuf:"bytes,2,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	IntValue   *UniformIntValue   `protobuf:"bytes,3,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	Texture    *UniformTexture    `protobuf:"bytes,4,opt,name=texture" json:"texture,omitempty"`
}

func (m *UniformVariable) Reset()                    { *m = UniformVariable{} }
func (m *UniformVariable) String() string            { return proto1.CompactTextString(m) }
func (*UniformVariable) ProtoMessage()               {}
func (*UniformVariable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UniformVariable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UniformVariable) GetFloatValue() *UniformFloatValue {
	if m != nil {
		return m.FloatValue
	}
	return nil
}

func (m *UniformVariable) GetIntValue() *UniformIntValue {
	if m != nil {
		return m.IntValue
	}
	return nil
}

func (m *UniformVariable) GetTexture() *UniformTexture {
	if m != nil {
		return m.Texture
	}
	return nil
}

type ArrayBuffer struct {
	Name string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data []float32 `protobuf:"fixed32,2,rep,packed,name=data" json:"data,omitempty"`
}

func (m *ArrayBuffer) Reset()                    { *m = ArrayBuffer{} }
func (m *ArrayBuffer) String() string            { return proto1.CompactTextString(m) }
func (*ArrayBuffer) ProtoMessage()               {}
func (*ArrayBuffer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ArrayBuffer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArrayBuffer) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type PaletteStates struct {
	// Shader
	VertexShader   string `protobuf:"bytes,1,opt,name=vertex_shader,json=vertexShader" json:"vertex_shader,omitempty"`
	FragmentShader string `protobuf:"bytes,2,opt,name=fragment_shader,json=fragmentShader" json:"fragment_shader,omitempty"`
	// VertexBuffer
	Buffers []*ArrayBuffer `protobuf:"bytes,3,rep,name=buffers" json:"buffers,omitempty"`
	// VertexElementBuffer
	Indecies []int32 `protobuf:"varint,4,rep,packed,name=indecies" json:"indecies,omitempty"`
	// VertexAttributes
	VertexArrtibutes []*VertexAttribute `protobuf:"bytes,5,rep,name=vertex_arrtibutes,json=vertexArrtibutes" json:"vertex_arrtibutes,omitempty"`
	// UniformVariables
	UniformVariables []*UniformVariable `protobuf:"bytes,6,rep,name=uniform_variables,json=uniformVariables" json:"uniform_variables,omitempty"`
}

func (m *PaletteStates) Reset()                    { *m = PaletteStates{} }
func (m *PaletteStates) String() string            { return proto1.CompactTextString(m) }
func (*PaletteStates) ProtoMessage()               {}
func (*PaletteStates) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PaletteStates) GetVertexShader() string {
	if m != nil {
		return m.VertexShader
	}
	return ""
}

func (m *PaletteStates) GetFragmentShader() string {
	if m != nil {
		return m.FragmentShader
	}
	return ""
}

func (m *PaletteStates) GetBuffers() []*ArrayBuffer {
	if m != nil {
		return m.Buffers
	}
	return nil
}

func (m *PaletteStates) GetIndecies() []int32 {
	if m != nil {
		return m.Indecies
	}
	return nil
}

func (m *PaletteStates) GetVertexArrtibutes() []*VertexAttribute {
	if m != nil {
		return m.VertexArrtibutes
	}
	return nil
}

func (m *PaletteStates) GetUniformVariables() []*UniformVariable {
	if m != nil {
		return m.UniformVariables
	}
	return nil
}

type UpdatePaletteRequest struct {
	EaselId   string         `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
	PaletteId string         `protobuf:"bytes,2,opt,name=palette_id,json=paletteId" json:"palette_id,omitempty"`
	States    *PaletteStates `protobuf:"bytes,3,opt,name=states" json:"states,omitempty"`
}

func (m *UpdatePaletteRequest) Reset()                    { *m = UpdatePaletteRequest{} }
func (m *UpdatePaletteRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdatePaletteRequest) ProtoMessage()               {}
func (*UpdatePaletteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdatePaletteRequest) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

func (m *UpdatePaletteRequest) GetPaletteId() string {
	if m != nil {
		return m.PaletteId
	}
	return ""
}

func (m *UpdatePaletteRequest) GetStates() *PaletteStates {
	if m != nil {
		return m.States
	}
	return nil
}

type UpdatePaletteResponse struct {
}

func (m *UpdatePaletteResponse) Reset()                    { *m = UpdatePaletteResponse{} }
func (m *UpdatePaletteResponse) String() string            { return proto1.CompactTextString(m) }
func (*UpdatePaletteResponse) ProtoMessage()               {}
func (*UpdatePaletteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// Render
type RenderRequest struct {
	EaselId    string         `protobuf:"bytes,1,opt,name=easel_id,json=easelId" json:"easel_id,omitempty"`
	PaletteId  string         `protobuf:"bytes,2,opt,name=palette_id,json=paletteId" json:"palette_id,omitempty"`
	States     *PaletteStates `protobuf:"bytes,3,opt,name=states" json:"states,omitempty"`
	OutQuality float32        `protobuf:"fixed32,4,opt,name=out_quality,json=outQuality" json:"out_quality,omitempty"`
	OutFormat  string         `protobuf:"bytes,5,opt,name=out_format,json=outFormat" json:"out_format,omitempty"`
	OutWidth   int32          `protobuf:"varint,6,opt,name=out_width,json=outWidth" json:"out_width,omitempty"`
	OutHeight  int32          `protobuf:"varint,7,opt,name=out_height,json=outHeight" json:"out_height,omitempty"`
}

func (m *RenderRequest) Reset()                    { *m = RenderRequest{} }
func (m *RenderRequest) String() string            { return proto1.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()               {}
func (*RenderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RenderRequest) GetEaselId() string {
	if m != nil {
		return m.EaselId
	}
	return ""
}

func (m *RenderRequest) GetPaletteId() string {
	if m != nil {
		return m.PaletteId
	}
	return ""
}

func (m *RenderRequest) GetStates() *PaletteStates {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *RenderRequest) GetOutQuality() float32 {
	if m != nil {
		return m.OutQuality
	}
	return 0
}

func (m *RenderRequest) GetOutFormat() string {
	if m != nil {
		return m.OutFormat
	}
	return ""
}

func (m *RenderRequest) GetOutWidth() int32 {
	if m != nil {
		return m.OutWidth
	}
	return 0
}

func (m *RenderRequest) GetOutHeight() int32 {
	if m != nil {
		return m.OutHeight
	}
	return 0
}

type RenderResponse struct {
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *RenderResponse) Reset()                    { *m = RenderResponse{} }
func (m *RenderResponse) String() string            { return proto1.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()               {}
func (*RenderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *RenderResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto1.RegisterType((*NewEaselRequest)(nil), "proto.NewEaselRequest")
	proto1.RegisterType((*NewEaselResponse)(nil), "proto.NewEaselResponse")
	proto1.RegisterType((*DeleteEaselRequest)(nil), "proto.DeleteEaselRequest")
	proto1.RegisterType((*DeleteEaselResponse)(nil), "proto.DeleteEaselResponse")
	proto1.RegisterType((*NewPaletteRequest)(nil), "proto.NewPaletteRequest")
	proto1.RegisterType((*NewPaletteResponse)(nil), "proto.NewPaletteResponse")
	proto1.RegisterType((*DeletePaletteRequest)(nil), "proto.DeletePaletteRequest")
	proto1.RegisterType((*DeletePaletteResponse)(nil), "proto.DeletePaletteResponse")
	proto1.RegisterType((*VertexAttribute)(nil), "proto.VertexAttribute")
	proto1.RegisterType((*UniformFloatValue)(nil), "proto.UniformFloatValue")
	proto1.RegisterType((*UniformIntValue)(nil), "proto.UniformIntValue")
	proto1.RegisterType((*UniformTexture)(nil), "proto.UniformTexture")
	proto1.RegisterType((*UniformVariable)(nil), "proto.UniformVariable")
	proto1.RegisterType((*ArrayBuffer)(nil), "proto.ArrayBuffer")
	proto1.RegisterType((*PaletteStates)(nil), "proto.PaletteStates")
	proto1.RegisterType((*UpdatePaletteRequest)(nil), "proto.UpdatePaletteRequest")
	proto1.RegisterType((*UpdatePaletteResponse)(nil), "proto.UpdatePaletteResponse")
	proto1.RegisterType((*RenderRequest)(nil), "proto.RenderRequest")
	proto1.RegisterType((*RenderResponse)(nil), "proto.RenderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EaselService service

type EaselServiceClient interface {
	// New/Delete
	NewEasel(ctx context.Context, in *NewEaselRequest, opts ...grpc.CallOption) (*NewEaselResponse, error)
	DeleteEasel(ctx context.Context, in *DeleteEaselRequest, opts ...grpc.CallOption) (*DeleteEaselResponse, error)
	NewPalette(ctx context.Context, in *NewPaletteRequest, opts ...grpc.CallOption) (*NewPaletteResponse, error)
	DeletePalette(ctx context.Context, in *DeletePaletteRequest, opts ...grpc.CallOption) (*DeletePaletteResponse, error)
	// Setup
	UpdatePalette(ctx context.Context, in *UpdatePaletteRequest, opts ...grpc.CallOption) (*UpdatePaletteResponse, error)
	// Render
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type easelServiceClient struct {
	cc *grpc.ClientConn
}

func NewEaselServiceClient(cc *grpc.ClientConn) EaselServiceClient {
	return &easelServiceClient{cc}
}

func (c *easelServiceClient) NewEasel(ctx context.Context, in *NewEaselRequest, opts ...grpc.CallOption) (*NewEaselResponse, error) {
	out := new(NewEaselResponse)
	err := grpc.Invoke(ctx, "/proto.EaselService/NewEasel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easelServiceClient) DeleteEasel(ctx context.Context, in *DeleteEaselRequest, opts ...grpc.CallOption) (*DeleteEaselResponse, error) {
	out := new(DeleteEaselResponse)
	err := grpc.Invoke(ctx, "/proto.EaselService/DeleteEasel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easelServiceClient) NewPalette(ctx context.Context, in *NewPaletteRequest, opts ...grpc.CallOption) (*NewPaletteResponse, error) {
	out := new(NewPaletteResponse)
	err := grpc.Invoke(ctx, "/proto.EaselService/NewPalette", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easelServiceClient) DeletePalette(ctx context.Context, in *DeletePaletteRequest, opts ...grpc.CallOption) (*DeletePaletteResponse, error) {
	out := new(DeletePaletteResponse)
	err := grpc.Invoke(ctx, "/proto.EaselService/DeletePalette", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easelServiceClient) UpdatePalette(ctx context.Context, in *UpdatePaletteRequest, opts ...grpc.CallOption) (*UpdatePaletteResponse, error) {
	out := new(UpdatePaletteResponse)
	err := grpc.Invoke(ctx, "/proto.EaselService/UpdatePalette", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easelServiceClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	out := new(RenderResponse)
	err := grpc.Invoke(ctx, "/proto.EaselService/Render", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EaselService service

type EaselServiceServer interface {
	// New/Delete
	NewEasel(context.Context, *NewEaselRequest) (*NewEaselResponse, error)
	DeleteEasel(context.Context, *DeleteEaselRequest) (*DeleteEaselResponse, error)
	NewPalette(context.Context, *NewPaletteRequest) (*NewPaletteResponse, error)
	DeletePalette(context.Context, *DeletePaletteRequest) (*DeletePaletteResponse, error)
	// Setup
	UpdatePalette(context.Context, *UpdatePaletteRequest) (*UpdatePaletteResponse, error)
	// Render
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
}

func RegisterEaselServiceServer(s *grpc.Server, srv EaselServiceServer) {
	s.RegisterService(&_EaselService_serviceDesc, srv)
}

func _EaselService_NewEasel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEaselRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).NewEasel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/NewEasel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).NewEasel(ctx, req.(*NewEaselRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EaselService_DeleteEasel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEaselRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).DeleteEasel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/DeleteEasel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).DeleteEasel(ctx, req.(*DeleteEaselRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EaselService_NewPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).NewPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/NewPalette",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).NewPalette(ctx, req.(*NewPaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EaselService_DeletePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).DeletePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/DeletePalette",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).DeletePalette(ctx, req.(*DeletePaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EaselService_UpdatePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).UpdatePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/UpdatePalette",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).UpdatePalette(ctx, req.(*UpdatePaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EaselService_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EaselService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EaselService",
	HandlerType: (*EaselServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewEasel",
			Handler:    _EaselService_NewEasel_Handler,
		},
		{
			MethodName: "DeleteEasel",
			Handler:    _EaselService_DeleteEasel_Handler,
		},
		{
			MethodName: "NewPalette",
			Handler:    _EaselService_NewPalette_Handler,
		},
		{
			MethodName: "DeletePalette",
			Handler:    _EaselService_DeletePalette_Handler,
		},
		{
			MethodName: "UpdatePalette",
			Handler:    _EaselService_UpdatePalette_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _EaselService_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "easel_service.proto",
}

func init() { proto1.RegisterFile("easel_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0x26, 0x09, 0xf9, 0x3b, 0x4e, 0x08, 0x0c, 0x04, 0x4c, 0xd8, 0xd5, 0x66, 0xbd, 0x2b, 0x6d,
	0x2e, 0x58, 0x90, 0x82, 0x56, 0xab, 0xbd, 0xd8, 0x0b, 0x96, 0x2d, 0x82, 0xaa, 0x8a, 0xa8, 0x53,
	0xe8, 0x65, 0x34, 0xc1, 0xc7, 0xc4, 0x92, 0x63, 0x87, 0xf1, 0x38, 0xfc, 0x5c, 0xf4, 0x81, 0x7a,
	0x53, 0xf5, 0x25, 0xfa, 0x42, 0x7d, 0x81, 0x6a, 0x7e, 0x9c, 0xc4, 0x49, 0x54, 0x50, 0x55, 0xf5,
	0xca, 0x9e, 0x6f, 0xbe, 0xf3, 0x9d, 0x9f, 0x39, 0x33, 0x07, 0x36, 0x91, 0x46, 0xe8, 0xf7, 0x22,
	0x64, 0x63, 0xef, 0x1a, 0x0f, 0x46, 0x2c, 0xe4, 0x21, 0xc9, 0xcb, 0x8f, 0xb5, 0x0f, 0xb5, 0x0e,
	0xde, 0xbd, 0x10, 0x04, 0x1b, 0x6f, 0x63, 0x8c, 0x38, 0xd9, 0x85, 0x92, 0x32, 0xf0, 0x1c, 0x33,
	0xd3, 0xcc, 0xb4, 0xca, 0x76, 0x51, 0xae, 0xcf, 0x1d, 0xeb, 0x4f, 0x58, 0x9f, 0xb2, 0xa3, 0x51,
	0x18, 0x44, 0xf8, 0x35, 0xfa, 0x21, 0x90, 0xff, 0xd1, 0x47, 0x8e, 0xcf, 0xd5, 0xaf, 0xc3, 0x66,
	0xca, 0x40, 0xb9, 0xb0, 0x0e, 0x60, 0xa3, 0x83, 0x77, 0x17, 0xd4, 0x47, 0xce, 0xf1, 0x19, 0x32,
	0x1d, 0x20, 0xb3, 0xfc, 0x27, 0x03, 0x25, 0x3f, 0x03, 0x8c, 0x14, 0x5b, 0x6c, 0x66, 0xe5, 0x66,
	0x59, 0x23, 0xe7, 0x8e, 0x75, 0x01, 0x5b, 0x2a, 0xac, 0x67, 0x87, 0xf0, 0x94, 0xe2, 0x0e, 0xd4,
	0xe7, 0x14, 0x75, 0xaa, 0xef, 0x33, 0x50, 0xbb, 0x42, 0xc6, 0xf1, 0xfe, 0x98, 0x73, 0xe6, 0xf5,
	0x63, 0x8e, 0xe4, 0x37, 0xa8, 0x52, 0x76, 0x13, 0x0f, 0x31, 0xe0, 0xbd, 0x80, 0x0e, 0x51, 0xfb,
	0xaa, 0x24, 0x60, 0x87, 0x0e, 0x91, 0xfc, 0x02, 0x46, 0x3f, 0x76, 0x5d, 0x64, 0x8a, 0xa2, 0x3c,
	0x82, 0x82, 0x24, 0xe1, 0x57, 0xa8, 0xa0, 0x8f, 0x52, 0x24, 0xf2, 0x1e, 0xd1, 0xcc, 0x35, 0x33,
	0xad, 0xbc, 0x6d, 0x68, 0xac, 0xeb, 0x3d, 0x22, 0xd9, 0x86, 0x42, 0xe8, 0xba, 0x11, 0x72, 0x73,
	0x55, 0x6e, 0xea, 0x95, 0xc0, 0x23, 0xce, 0x3c, 0x07, 0xcd, 0xbc, 0xc2, 0xd5, 0xca, 0x7a, 0x09,
	0x1b, 0x97, 0x81, 0xe7, 0x86, 0x6c, 0x78, 0xea, 0x87, 0x94, 0x5f, 0x51, 0x3f, 0x5e, 0xf4, 0x93,
	0x59, 0xf4, 0x43, 0x60, 0xd5, 0xa1, 0x9c, 0x9a, 0xd9, 0x66, 0xae, 0x95, 0xb5, 0xe5, 0xbf, 0x75,
	0x06, 0x35, 0xad, 0x75, 0x1e, 0x7c, 0x9b, 0x52, 0x5e, 0x2b, 0xfd, 0x0e, 0x6b, 0x5a, 0xe9, 0x0d,
	0xde, 0xf3, 0x98, 0x4d, 0x59, 0x42, 0xa0, 0xa2, 0x59, 0x9f, 0x32, 0x13, 0x87, 0x57, 0x94, 0x79,
	0xb4, 0xef, 0x4b, 0xde, 0x4c, 0x7d, 0xe5, 0x3f, 0xf9, 0x07, 0x0c, 0x57, 0x24, 0xd7, 0x1b, 0x8b,
	0x98, 0x64, 0x5d, 0x8d, 0xb6, 0xa9, 0x2e, 0xd1, 0xc1, 0x42, 0xf6, 0x36, 0xb8, 0xd3, 0x4a, 0x1c,
	0x41, 0xd9, 0x0b, 0x12, 0xc3, 0x9c, 0x34, 0xdc, 0x4e, 0x1b, 0x26, 0xa9, 0xda, 0x25, 0x2f, 0x49,
	0xfa, 0x10, 0x8a, 0x5c, 0x85, 0x2d, 0x0f, 0xc1, 0x68, 0xd7, 0xd3, 0x26, 0x3a, 0x27, 0x3b, 0x61,
	0x59, 0x7f, 0x81, 0x71, 0xcc, 0x18, 0x7d, 0xf8, 0x4f, 0x1e, 0xf5, 0xd2, 0x1c, 0x96, 0xd5, 0xfb,
	0x63, 0x16, 0xaa, 0xba, 0xf9, 0xba, 0x9c, 0x72, 0x8c, 0x44, 0x9b, 0x8d, 0x65, 0xe7, 0xf5, 0xa2,
	0x01, 0x75, 0x90, 0x25, 0x6d, 0xa6, 0xc0, 0xae, 0xc4, 0xc8, 0x1f, 0x50, 0x73, 0x19, 0xbd, 0x51,
	0x87, 0xa2, 0x68, 0xaa, 0xd5, 0xd6, 0x12, 0x58, 0x13, 0xf7, 0xa1, 0xa8, 0x9a, 0x2f, 0x32, 0x73,
	0xcd, 0x5c, 0xcb, 0x68, 0x13, 0x9d, 0xc7, 0x4c, 0xb0, 0x76, 0x42, 0x21, 0x0d, 0x28, 0x79, 0x81,
	0x83, 0xd7, 0x1e, 0x46, 0xe6, 0xaa, 0x3c, 0xcb, 0xc9, 0x9a, 0x9c, 0xc0, 0x86, 0x8e, 0x8b, 0x32,
	0xc6, 0xe5, 0x95, 0x88, 0xcc, 0xbc, 0xd4, 0x4c, 0xca, 0x39, 0x77, 0x63, 0xec, 0x75, 0x65, 0x70,
	0x3c, 0xe1, 0x0b, 0x91, 0x58, 0x15, 0xb0, 0x37, 0xd6, 0xc7, 0x1d, 0x99, 0x85, 0x94, 0xc8, 0x5c,
	0x37, 0xd8, 0xeb, 0x71, 0x1a, 0x88, 0xac, 0x77, 0xb0, 0x75, 0x39, 0x72, 0xe8, 0xf7, 0x7b, 0x07,
	0xc8, 0xbe, 0xb8, 0x59, 0xa2, 0xfa, 0xba, 0x3f, 0xb6, 0x74, 0x2c, 0xa9, 0x93, 0xb1, 0x35, 0x47,
	0xbc, 0x1a, 0x73, 0xfe, 0xf5, 0xab, 0xf1, 0x39, 0x03, 0x55, 0x1b, 0x03, 0x07, 0xd9, 0x0f, 0x0e,
	0x49, 0x3c, 0x3b, 0x61, 0xcc, 0x7b, 0xb7, 0x31, 0xf5, 0x3d, 0xfe, 0x20, 0x5b, 0x36, 0x6b, 0x43,
	0x18, 0xf3, 0xd7, 0x0a, 0x11, 0xde, 0x04, 0x41, 0x14, 0x92, 0x72, 0xf9, 0x7e, 0x94, 0xed, 0x72,
	0x18, 0xf3, 0x53, 0x09, 0x90, 0x3d, 0x10, 0x8b, 0xde, 0x9d, 0xe7, 0xf0, 0x81, 0x59, 0x90, 0x17,
	0xbc, 0x14, 0xc6, 0xfc, 0xad, 0x58, 0x27, 0xb6, 0x03, 0xf4, 0x6e, 0x06, 0xdc, 0x2c, 0xca, 0x5d,
	0x41, 0x3f, 0x93, 0x80, 0xd5, 0x82, 0xb5, 0x24, 0x69, 0xfd, 0xc4, 0x8b, 0x07, 0x2c, 0xe6, 0xa3,
	0x98, 0xeb, 0xab, 0xae, 0x57, 0xed, 0x0f, 0x39, 0xa8, 0xc8, 0x91, 0xd2, 0x55, 0x33, 0x90, 0xfc,
	0x0b, 0xa5, 0x64, 0x90, 0x91, 0xe4, 0xfc, 0xe7, 0xe6, 0x60, 0x63, 0x67, 0x01, 0xd7, 0xd5, 0x5e,
	0x21, 0xa7, 0x60, 0xcc, 0xcc, 0x29, 0xb2, 0xab, 0x99, 0x8b, 0xc3, 0xae, 0xd1, 0x58, 0xb6, 0x35,
	0xd1, 0x39, 0x01, 0x98, 0x0e, 0x2a, 0x62, 0x4e, 0x1d, 0xa6, 0x1b, 0xac, 0xb1, 0xbb, 0x64, 0x67,
	0x22, 0xf2, 0x0a, 0xaa, 0xa9, 0x59, 0x42, 0xf6, 0x52, 0x3e, 0xe7, 0xa4, 0x7e, 0x5a, 0xbe, 0x39,
	0xab, 0x96, 0xea, 0xb1, 0x89, 0xda, 0xb2, 0xce, 0x9f, 0xa8, 0x2d, 0x6f, 0xcb, 0x15, 0xf2, 0x37,
	0x14, 0xd4, 0x11, 0x91, 0xa4, 0x8d, 0x52, 0x6d, 0xda, 0xa8, 0xcf, 0xa1, 0x89, 0x61, 0xbf, 0x20,
	0xf1, 0xa3, 0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x3b, 0x7c, 0xbf, 0xbc, 0x08, 0x00, 0x00,
}
