// Code generated by protoc-gen-go.
// source: easel_service.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	easel_service.proto

It has these top-level messages:
	ResponseType
	RequestType
	Person
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseType struct {
}

func (m *ResponseType) Reset()                    { *m = ResponseType{} }
func (m *ResponseType) String() string            { return proto1.CompactTextString(m) }
func (*ResponseType) ProtoMessage()               {}
func (*ResponseType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RequestType struct {
}

func (m *RequestType) Reset()                    { *m = RequestType{} }
func (m *RequestType) String() string            { return proto1.CompactTextString(m) }
func (*RequestType) ProtoMessage()               {}
func (*RequestType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Person struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto1.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto1.RegisterType((*ResponseType)(nil), "proto.ResponseType")
	proto1.RegisterType((*RequestType)(nil), "proto.RequestType")
	proto1.RegisterType((*Person)(nil), "proto.Person")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EaselService service

type EaselServiceClient interface {
	ListPerson(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (EaselService_ListPersonClient, error)
	AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*ResponseType, error)
}

type easelServiceClient struct {
	cc *grpc.ClientConn
}

func NewEaselServiceClient(cc *grpc.ClientConn) EaselServiceClient {
	return &easelServiceClient{cc}
}

func (c *easelServiceClient) ListPerson(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (EaselService_ListPersonClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EaselService_serviceDesc.Streams[0], c.cc, "/proto.EaselService/ListPerson", opts...)
	if err != nil {
		return nil, err
	}
	x := &easelServiceListPersonClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EaselService_ListPersonClient interface {
	Recv() (*Person, error)
	grpc.ClientStream
}

type easelServiceListPersonClient struct {
	grpc.ClientStream
}

func (x *easelServiceListPersonClient) Recv() (*Person, error) {
	m := new(Person)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *easelServiceClient) AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*ResponseType, error) {
	out := new(ResponseType)
	err := grpc.Invoke(ctx, "/proto.EaselService/AddPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EaselService service

type EaselServiceServer interface {
	ListPerson(*RequestType, EaselService_ListPersonServer) error
	AddPerson(context.Context, *Person) (*ResponseType, error)
}

func RegisterEaselServiceServer(s *grpc.Server, srv EaselServiceServer) {
	s.RegisterService(&_EaselService_serviceDesc, srv)
}

func _EaselService_ListPerson_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EaselServiceServer).ListPerson(m, &easelServiceListPersonServer{stream})
}

type EaselService_ListPersonServer interface {
	Send(*Person) error
	grpc.ServerStream
}

type easelServiceListPersonServer struct {
	grpc.ServerStream
}

func (x *easelServiceListPersonServer) Send(m *Person) error {
	return x.ServerStream.SendMsg(m)
}

func _EaselService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EaselServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EaselService/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EaselServiceServer).AddPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

var _EaselService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EaselService",
	HandlerType: (*EaselServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _EaselService_AddPerson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPerson",
			Handler:       _EaselService_ListPerson_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "easel_service.proto",
}

func init() { proto1.RegisterFile("easel_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4d, 0x2c, 0x4e,
	0xcd, 0x89, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x53, 0x4a, 0x7c, 0x5c, 0x3c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x21,
	0x95, 0x05, 0xa9, 0x4a, 0xbc, 0x5c, 0xdc, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x60, 0xae,
	0x1e, 0x17, 0x5b, 0x40, 0x6a, 0x51, 0x71, 0x7e, 0x9e, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e,
	0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x9e,
	0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x62, 0x1a, 0x95, 0x71, 0xf1, 0xb8, 0x82, 0x2c,
	0x0b, 0x86, 0xd8, 0x25, 0x64, 0xcc, 0xc5, 0xe5, 0x93, 0x59, 0x5c, 0x02, 0x33, 0x03, 0x62, 0xb7,
	0x1e, 0x92, 0x0d, 0x52, 0xbc, 0x50, 0x31, 0x88, 0x12, 0x25, 0x06, 0x03, 0x46, 0x21, 0x43, 0x2e,
	0x4e, 0xc7, 0x94, 0x14, 0xa8, 0x1e, 0x54, 0x79, 0x29, 0x61, 0xb8, 0x11, 0x48, 0x8e, 0x66, 0x48,
	0x62, 0x03, 0x8b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x99, 0xff, 0x2f, 0x76, 0xeb, 0x00,
	0x00, 0x00,
}
